# Generated by Django 4.1.4 on 2023-02-02 17:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0009_alter_brand_brand_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon_code', models.CharField(max_length=10, unique=True, verbose_name='کد کوپن')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'کوپن تخفیف',
                'verbose_name_plural': 'کوپن ها',
                'db_table': 'cupon',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CuponBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_title', models.CharField(max_length=100, verbose_name='عنوان سبد تخفیف')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(verbose_name='تاریخ پایان')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='درصد تخفیف')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'سبد تخفیف',
                'verbose_name_plural': 'سبد های تخفیف',
                'db_table': 'cuponbasket',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CuponBasketDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon_basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuponbasketdetail1', to='discount.cuponbasket', verbose_name='سبد تخفیف')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuponbasketdetail2', to='product.product', verbose_name='کالا ')),
            ],
            options={
                'verbose_name': '  جزییات سبد تخفیف',
                'verbose_name_plural': '  جزییات سبد های تخفیف ',
                'db_table': 'cuponbasketdetail',
                'managed': True,
            },
        ),
    ]
