# Generated by Django 4.1.4 on 2023-02-02 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_payment_order_description_alter_order_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.payment', verbose_name='روش پرداخت'),
        ),
        migrations.AlterField(
            model_name='order',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 2, 15, 4, 25, 264555), verbose_name='تاریخ درج سفارش'),
        ),
    ]
