# Generated by Django 4.1.4 on 2023-03-04 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 4, 12, 44, 0, 602317), verbose_name='تاریخ درج سفارش'),
        ),
    ]
