# Generated by Django 4.1.4 on 2023-03-04 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 4, 18, 48, 13, 259830), verbose_name='تاریخ درج سفارش'),
        ),
    ]
