# Generated by Django 4.1.4 on 2023-03-05 16:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_register_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 5, 16, 10, 59, 71327), verbose_name='تاریخ درج سفارش'),
        ),
    ]
