# Generated by Django 4.1.4 on 2022-12-13 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='regester_date',
            field=models.DateField(default=datetime.datetime(2022, 12, 13, 15, 4, 6, 415898)),
        ),
    ]
