# Generated by Django 4.1.4 on 2023-01-15 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customeruser_regester_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='regester_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 15, 15, 21, 47, 696620)),
        ),
    ]
