# Generated by Django 4.1.4 on 2023-02-01 15:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utilis


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_customeruser_regester_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('image_name', models.ImageField(upload_to=utilis.FileUpload.imageupload, verbose_name='تصویر پروفایل')),
            ],
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='regester_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 1, 15, 5, 28, 303974)),
        ),
    ]
