# Generated by Django 4.1.4 on 2022-12-20 21:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utilis


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=50, verbose_name='نام برند')),
                ('brand_image', models.ImageField(upload_to=utilis.FileUpload.imageupload, verbose_name='تصویر برند')),
                ('slug', models.SlugField(max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برندها',
                'db_table': 'brand',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=50, verbose_name='نام ویژگی')),
            ],
            options={
                'verbose_name': 'ویژگی',
                'verbose_name_plural': 'ویژگی ها',
                'db_table': 'feature',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grouppro_name', models.CharField(max_length=50, verbose_name='نام گروه کالا')),
                ('grouppro_image', models.ImageField(upload_to=utilis.FileUpload.imageupload, verbose_name='تصویر گروه کالا')),
                ('grouppro_description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال/غیر فعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name=' تاریخ درج')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update', models.DateTimeField(auto_now=True, verbose_name=' تاریخ اخرین بروزرسانی')),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('group_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='product.groupproduct', verbose_name='والد گروه کالا')),
            ],
            options={
                'verbose_name': 'گروه کالا',
                'verbose_name_plural': 'گروه های کالاها',
                'db_table': 'groupproduct',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, verbose_name='نام کالا')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت کالا')),
                ('product_image', models.ImageField(upload_to=utilis.FileUpload.imageupload, verbose_name='تصویر  کالا')),
                ('product_description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال/غیر فعال')),
                ('register_date', models.DateTimeField(auto_now_add=True, verbose_name=' تاریخ درج')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ انتشار')),
                ('update', models.DateTimeField(auto_now=True, verbose_name=' تاریخ اخرین بروزرسانی')),
                ('slug', models.SlugField(max_length=100, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brands', to='product.brand', verbose_name='برند کالا')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50, verbose_name='مقدار ویژگی کالا')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.feature', verbose_name=' ویژگی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name=' کالا')),
            ],
            options={
                'verbose_name': 'ویژگی محصول',
                'verbose_name_plural': 'ویژگی محصولات',
                'db_table': 'productfeature',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='features',
            field=models.ManyToManyField(through='product.ProductFeature', to='product.feature', verbose_name='گروه کالا'),
        ),
        migrations.AddField(
            model_name='product',
            name='group_pro',
            field=models.ManyToManyField(related_name='product_of_group', to='product.groupproduct', verbose_name='گروه کالا'),
        ),
        migrations.CreateModel(
            name='GaleryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(upload_to=utilis.FileUpload.imageupload, verbose_name='تصاویر کالا')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
                'db_table': 'galeryproduct',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='group_PRODUCT',
            field=models.ManyToManyField(related_name='feature_of_group', to='product.groupproduct', verbose_name='گروه کالا'),
        ),
    ]
