# Generated by Django 4.1.4 on 2022-12-29 01:11

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import utilis


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True, 'verbose_name': 'کالا', 'verbose_name_plural': 'کالاها'},
        ),
        migrations.AddField(
            model_name='product',
            name='full_description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(upload_to=utilis.FileUpload.imageupload, verbose_name='تصویر برند'),
        ),
        migrations.AlterField(
            model_name='galeryproduct',
            name='product_image',
            field=models.ImageField(upload_to=utilis.FileUpload.imageupload, verbose_name='تصاویر کالا'),
        ),
        migrations.AlterField(
            model_name='galeryproduct',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galery_of_product', to='product.product', verbose_name='کالا'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='grouppro_image',
            field=models.ImageField(upload_to=utilis.FileUpload.imageupload, verbose_name='تصویر گروه کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to=utilis.FileUpload.imageupload, verbose_name='تصویر  کالا'),
        ),
        migrations.AlterField(
            model_name='productfeature',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_pro', to='product.product', verbose_name=' کالا'),
        ),
    ]
