# Generated by Django 4.1.4 on 2023-01-15 15:21

from django.db import migrations, models
import django.db.models.deletion
import utilis


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_brand_brand_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(upload_to=utilis.FileUpload.imageupload, verbose_name='تصویر برند'),
        ),
        migrations.AlterField(
            model_name='galeryproduct',
            name='product_image',
            field=models.ImageField(upload_to=utilis.FileUpload.imageupload, verbose_name='تصاویر کالا'),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='grouppro_image',
            field=models.ImageField(upload_to=utilis.FileUpload.imageupload, verbose_name='تصویر گروه کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to=utilis.FileUpload.imageupload, verbose_name='تصویر  کالا'),
        ),
        migrations.CreateModel(
            name='FeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_title', models.CharField(max_length=100, verbose_name='عنوان مقدار')),
                ('feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_feature_value', to='product.feature', verbose_name=' ویژگی')),
            ],
            options={
                'verbose_name': 'مقدار ویژگی',
                'verbose_name_plural': 'مقادیر ویژگی ها',
                'db_table': 'featurevalue',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='productfeature',
            name='filter_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_filter_value', to='product.featurevalue', verbose_name=' مقادیر ویزگی انتخابی'),
        ),
    ]
